### ISSUE TITLE
Create CI for Ensuring Link Validity

### ISSUE THREAD

**Issue by ckohen** [IanMitchell/hackweek-discord-api-docs#30]
Many things to do, here they are

## Action

- [x] Install node
- [x] Install deps
- [x] Run build:ci
- [x] Run test:links (needs build)

## Code

- [x] File scan for all html files in `./.next/server/pages` and subdirectories
- [x] Read each file, parse as html ([jsdom](https://www.npmjs.com/package/jsdom)?)
- [x] Create a map of files to their anchors
  - [x] Map key is the path minus .html
  - [x] Scan the DOM within the `main` element for all ids, these are the valid anchors for the file
- [x] In order to provide useful results, scan all .mdx files in `./pages` as text
- [x] For each line in a file, scan for markdown link syntax.
- [x] When a link is found, check if it exists in the map
  - [x] If yes, move on
  - [x] If no, add to results output with line number and column number, move on
- [x] Scan Nav file for `href=` and check valid links
- [x] Print Results (user results maybe snag [eslints default output style](https://github.com/eslint/eslint/blob/master/lib/cli-engine/formatters/stylish.js) 👀)
- [x] Use [@actions/core](https://www.npmjs.com/package/@actions/core) to give CI annotations when run in CI

**Comment by IanMitchell** [comment]
godspeed
