### ISSUE TITLE
Style Alert types

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/hackweek-discord-api-docs#5]
Soriquato is taking a look at this

**Comment by Soriquato** [comment]
I might encounter a lot of struggles doing that, already made a PR that is actually wrong, so yeah. I'm also encountering problems compiling the css files while trying to read the docs so yeah, any help would be much appreciated

**Comment by Soriquato** [comment]
Done in #18, need a review before merging thanks ^^
